version: '3.8'

services:
  postgres:
    image: postgres:15-alpine # Use a specific version of PostgreSQL
    environment:
      POSTGRES_USER: postgres # Set your PostgreSQL username
      POSTGRES_PASSWORD: postgres # Set your PostgreSQL password
      POSTGRES_DB: computer-repair-shop # Set your default database name
    volumes:
      - .dbdata:/var/lib/postgresql/data # Persist data in a volume on cwd
    ports:
      - '5432:5432' # Expose PostgreSQL on port 5432
